<a href="https://colab.research.google.com/github/Naga-SDonepudi/PyTorch_HandsOn/blob/main/1_Fundamentals_of_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing PyTorch

In [2]:
import torch
print("PyTorch Version:", torch.__version__)

PyTorch Version: 2.9.0+cpu


## Importing Pandas, NumPy, Matplotlib

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Pandas Version:", pd.__version__)
print("NumPy Version:", np.__version__)

Pandas Version: 2.2.2
NumPy Version: 2.0.2


## Tensors
* A mutli dimensional array of numbers used to store machine learning and deep learning related data. PyTorch tensors are created using torch.tensor()

In [4]:
### Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
### Vector
vector = torch.tensor([8, 8])
vector

tensor([8, 8])

In [6]:
### Matrix
matrix = torch.tensor([[2,4],
                       [3,5]])
matrix

tensor([[2, 4],
        [3, 5]])

In [7]:
matrix.shape

torch.Size([2, 2])

In [8]:
### TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [9]:
TENSOR.ndim

3

## Random Tensors
* A random tensor is a tensor whose values are randomly generated and filled with random numbers, useful for starting models, testing, and experiments.
* They are widely used in machine learning and deep learning to initialize model weights, create dummy data, and test code.
* Random numbers are so valuable, as neural networks start with random numbers and looks at data, and adjusts those numbers and so on.


In [10]:
random_tensor = torch.rand(2, 3)
random_tensor

tensor([[0.9251, 0.3174, 0.4200],
        [0.1194, 0.9560, 0.1361]])

In [11]:
random_tensor.ndim

2

In [12]:
# A random image tensor with (height, width and color channels R,G,B)
random_image_size_tensor = torch.rand(size=(186, 186, 8))
random_image_size_tensor

tensor([[[0.5558, 0.2687, 0.3739,  ..., 0.4740, 0.8856, 0.9840],
         [0.7537, 0.1251, 0.8551,  ..., 0.3236, 0.3096, 0.1087],
         [0.0077, 0.8043, 0.9172,  ..., 0.8207, 0.1904, 0.4477],
         ...,
         [0.1502, 0.2106, 0.3637,  ..., 0.0669, 0.0592, 0.5156],
         [0.2681, 0.2638, 0.1835,  ..., 0.5805, 0.1979, 0.2278],
         [0.1748, 0.1735, 0.9817,  ..., 0.8936, 0.0412, 0.5762]],

        [[0.3686, 0.2199, 0.9462,  ..., 0.4009, 0.2938, 0.2165],
         [0.8404, 0.0799, 0.5999,  ..., 0.8274, 0.3716, 0.0096],
         [0.3391, 0.7225, 0.6269,  ..., 0.7500, 0.4066, 0.2273],
         ...,
         [0.7389, 0.9606, 0.6456,  ..., 0.0823, 0.7667, 0.3187],
         [0.9989, 0.8995, 0.7310,  ..., 0.7492, 0.8222, 0.0468],
         [0.9905, 0.8862, 0.1072,  ..., 0.0489, 0.6330, 0.3755]],

        [[0.5464, 0.5706, 0.6137,  ..., 0.4427, 0.4299, 0.5015],
         [0.8955, 0.3149, 0.2800,  ..., 0.0727, 0.2712, 0.2969],
         [0.8912, 0.5506, 0.0154,  ..., 0.5716, 0.2672, 0.

In [13]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([186, 186, 8]))

## Ones and Zeros Tensors

In [23]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
# Checking shape and dimension
zeros.shape, zeros.ndim

(torch.Size([3, 4]), 2)

In [34]:
ones = torch.ones(size=(3,3,4))
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [35]:
ones.ndim

3

## Range of tensors and tensor-likes

In [36]:
## Creating a range of tensors
one_to_hundred = torch.arange(1, 101, 9)
one_to_hundred

tensor([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100])

In [37]:
## Creating tensors like
ten_ones = torch.ones_like(input=one_to_hundred)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Datatypes of Tensors


In [38]:
dt_tensor = torch.tensor([1.0, 2.0, 3.0],
                         dtype=None, # Type Data
                         device=None, # What device is tensor on
                         requires_grad=False) # Whether or not to track gradients with this tensor operation

In [45]:
dt_tensor.dtype

torch.float32

In [48]:
# Changing the dtype from LongTensor(32-bit) to HalfTensor (16-bit)
dt_half_tensor = dt_tensor.type(torch.HalfTensor)
dt_half_tensor

tensor([1., 2., 3.], dtype=torch.float16)

## Tensor Attributes

In [41]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6588, 0.1520, 0.8415, 0.4552],
        [0.2504, 0.4643, 0.5387, 0.3921],
        [0.1332, 0.0137, 0.9645, 0.9179]])

In [44]:
print(some_tensor)
print(f"Tensor's Datatype: {some_tensor.dtype}")
print(f"Tensor's Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.6588, 0.1520, 0.8415, 0.4552],
        [0.2504, 0.4643, 0.5387, 0.3921],
        [0.1332, 0.0137, 0.9645, 0.9179]])
Tensor's Datatype: torch.float32
Tensor's Shape: torch.Size([3, 4])
Device: cpu


## Mnaipulating Tensors
* Tensor operations include:
  * addition
  * multiplication
  * subtraction
  * division
  * matrix multiplication

In [63]:
# Tensor Operations, lets start creating a tensor and adding 6
tensor = torch.tensor([1,3,5])
tensor + 6

tensor([ 7,  9, 11])

In [65]:
# Multiplying with operation and PyTorch inbuilt functions
tensor * 8

tensor([ 8, 24, 40])

In [70]:
# Subtracting
tensor - 3

tensor([-2,  0,  2])

### Performing the same operations using PyTorch builtin Functions

In [72]:
torch.add(tensor, 6), torch.mul(tensor, 8), torch.sub(tensor, 3)

(tensor([ 7,  9, 11]), tensor([ 8, 24, 40]), tensor([-2,  0,  2]))