<a href="https://colab.research.google.com/github/Naga-SDonepudi/PyTorch_HandsOn/blob/main/1_Fundamentals_of_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Intro
* An open source framework used for **Machine Learing, Deep Learning and Neural Networks**.
* It offers flexible tensor computation with strong **GPU acceleration** and tools for building and **deploying neural networks**.
* Easy to use PyTorch when compared to TensorFlow, because it is better for learning and experimenting.
* Tensor is how the data is represented in PyTorch. It is a **multi dimensional** array which can run math operations on CPU or GPU.
* **torch.tensor** is used to create a tensor, a basic data structure in PyTorch.

# Importing PyTorch

In [1]:
import torch
print("PyTorch Version:", torch.__version__)

PyTorch Version: 2.9.0+cpu


## Importing Pandas, NumPy, Matplotlib

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Pandas Version:", pd.__version__)
print("NumPy Version:", np.__version__)

Pandas Version: 2.2.2
NumPy Version: 2.0.2


## Tensors
* A mutli dimensional array of numbers used to store machine learning and deep learning related data. PyTorch tensors are created using torch.tensor()

In [3]:
### Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
### Vector
vector = torch.tensor([8, 8])
vector

tensor([8, 8])

In [5]:
### Matrix
matrix = torch.tensor([[2,4],
                       [3,5]])
matrix

tensor([[2, 4],
        [3, 5]])

In [6]:
matrix.shape

torch.Size([2, 2])

In [7]:
### TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [8]:
TENSOR.ndim

3

## Random Tensors
* A random tensor is a tensor whose values are randomly generated and filled with random numbers, useful for starting models, testing, and experiments.
* They are widely used in machine learning and deep learning to initialize model weights, create dummy data, and test code.
* Random numbers are so valuable, as neural networks start with random numbers and looks at data, and adjusts those numbers and so on.


In [9]:
random_tensor = torch.rand(2, 3)
random_tensor

tensor([[0.3321, 0.4067, 0.1942],
        [0.7021, 0.9248, 0.3540]])

In [10]:
random_tensor.ndim

2

In [11]:
# A random image tensor with (height, width and color channels R,G,B)
random_image_size_tensor = torch.rand(size=(186, 186, 8))
random_image_size_tensor

tensor([[[0.2868, 0.2763, 0.2502,  ..., 0.9247, 0.4361, 0.9604],
         [0.0024, 0.8953, 0.8459,  ..., 0.5253, 0.1992, 0.9709],
         [0.0945, 0.4887, 0.3661,  ..., 0.5223, 0.2209, 0.4847],
         ...,
         [0.8709, 0.6863, 0.3267,  ..., 0.6709, 0.1185, 0.3187],
         [0.3663, 0.6398, 0.1662,  ..., 0.0916, 0.1699, 0.2904],
         [0.6868, 0.9312, 0.3895,  ..., 0.8529, 0.6290, 0.7229]],

        [[0.8954, 0.7485, 0.4791,  ..., 0.8961, 0.0208, 0.9447],
         [0.4527, 0.6354, 0.4551,  ..., 0.6754, 0.4936, 0.9805],
         [0.6700, 0.1306, 0.9986,  ..., 0.7683, 0.5878, 0.5461],
         ...,
         [0.2094, 0.6187, 0.3022,  ..., 0.8678, 0.3982, 0.2388],
         [0.2651, 0.9149, 0.5368,  ..., 0.0107, 0.3709, 0.0661],
         [0.4630, 0.3254, 0.0872,  ..., 0.0742, 0.5265, 0.6556]],

        [[0.5054, 0.8571, 0.4984,  ..., 0.4771, 0.0521, 0.2863],
         [0.7396, 0.3091, 0.7267,  ..., 0.4290, 0.2317, 0.1945],
         [0.3773, 0.4976, 0.3378,  ..., 0.4158, 0.4966, 0.

In [12]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([186, 186, 8]))

## Ones and Zeros Tensors

In [13]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
# Checking shape and dimension
zeros.shape, zeros.ndim

(torch.Size([3, 4]), 2)

In [15]:
ones = torch.ones(size=(3,3,4))
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [16]:
ones.ndim

3

## Range of tensors and tensor-likes

In [17]:
## Creating a range of tensors
one_to_hundred = torch.arange(1, 101, 9)
one_to_hundred

tensor([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100])

In [18]:
## Creating tensors like
ten_ones = torch.ones_like(input=one_to_hundred)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Datatypes of Tensors


In [19]:
dt_tensor = torch.tensor([1.0, 2.0, 3.0],
                         dtype=None, # Type Data
                         device=None, # What device is tensor on
                         requires_grad=False) # Whether or not to track gradients with this tensor operation

In [20]:
dt_tensor.dtype

torch.float32

In [21]:
# Changing the dtype from LongTensor(32-bit) to HalfTensor (16-bit)
dt_half_tensor = dt_tensor.type(torch.HalfTensor)
dt_half_tensor

tensor([1., 2., 3.], dtype=torch.float16)

## Tensor Attributes

In [22]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1951, 0.4431, 0.4954, 0.0674],
        [0.8670, 0.2757, 0.2870, 0.3398],
        [0.3818, 0.1115, 0.6799, 0.4445]])

In [23]:
print(some_tensor)
print(f"Tensor's Datatype: {some_tensor.dtype}")
print(f"Tensor's Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.1951, 0.4431, 0.4954, 0.0674],
        [0.8670, 0.2757, 0.2870, 0.3398],
        [0.3818, 0.1115, 0.6799, 0.4445]])
Tensor's Datatype: torch.float32
Tensor's Shape: torch.Size([3, 4])
Device: cpu


## Mnaipulating Tensors
* Tensor operations include:
  * addition
  * multiplication
  * subtraction
  * division
  * matrix multiplication

In [24]:
# Tensor Operations, lets start creating a tensor and adding 6
tensor = torch.tensor([1,3,5])
tensor + 6

tensor([ 7,  9, 11])

In [25]:
# Multiplying with operation and PyTorch inbuilt functions
tensor * 8

tensor([ 8, 24, 40])

In [26]:
# Subtracting
tensor - 3

tensor([-2,  0,  2])

### Performing the same operations using PyTorch builtin Functions

In [27]:
torch.add(tensor, 6), torch.mul(tensor, 8), torch.sub(tensor, 3)

(tensor([ 7,  9, 11]), tensor([ 8, 24, 40]), tensor([-2,  0,  2]))

### Matrix Multiplication
Two ways:
* Elementi-wise multiplication
* Matrix Multiplication

In [28]:
# Element wise
print(tensor, "*", tensor)
print(f"Is: {tensor * tensor}")

tensor([1, 3, 5]) * tensor([1, 3, 5])
Is: tensor([ 1,  9, 25])


In [29]:
# Matrix Multiplication using Pytorch inbuilt function
torch.matmul(tensor, tensor)

tensor(35)

In [30]:
# Checking the execution time while using for loop
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.54 ms, sys: 0 ns, total: 1.54 ms
Wall time: 9.17 ms


tensor(35)

In [31]:
# checking execution time while using PyTorch matmul fucntion
%%time
torch.matmul(tensor, tensor)

CPU times: user 879 µs, sys: 0 ns, total: 879 µs
Wall time: 889 µs


tensor(35)

## Two main rules for matrix multiplication
1. The inner dimensions must match ie **(3,4) @ (4,3)**
2. Then the matrix results will have the shape of **outer dimensions**

## Shape Errors
* Here, I have performed a matmul fucntion, but it returned an error
* So, used a transpose T to fix out the tensor shape of tensor_b
* T switches the dimensions of a tensor

In [32]:
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_b = torch.tensor([[7,8],
                         [9,10],
                         [11,12]]).T
torch.matmul(tensor_a, tensor_b), torch.matmul(tensor_a, tensor_b).shape

(tensor([[ 23,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]]),
 torch.Size([3, 3]))

In [33]:
# tensor_b after transpose
tensor_b

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [34]:
print(f"Given data Shapes: tensor_a = {tensor_a.shape}, tensor_b = {tensor_b.shape}")
print(f"Transposed data shape: tensor_b.T = {tensor_b.shape}")
print(f"\nOutput is: \n{torch.matmul(tensor_a, tensor_b)}")
print(f"\nOutput shape: {torch.matmul(tensor_a, tensor_b).shape}")

Given data Shapes: tensor_a = torch.Size([3, 2]), tensor_b = torch.Size([2, 3])
Transposed data shape: tensor_b.T = torch.Size([2, 3])

Output is: 
tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


## Tensor Aggregations
* min
* max
* mean (it wont work on data type long int64, so chnaged to float32)
* sum

In [35]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
# Finding MIN, MAX, MEAN, SUM
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(0), tensor(90), tensor(45.), tensor(450))

## Finding the positional min and max

In [37]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
# argmin is used to find and return the index position of minimum value
torch.argmin(x)

tensor(0)

In [39]:
# argmax is used to find and return the index position of maximum value
torch.argmax(x)

tensor(9)

## PyTorch Tensors and NumPy
* NumPy and Tensors are used to store, and manipulate numeric data but the difference lies in their purpose.
* NumPy is for data analysis and numerical computing.
* Pytorch tensors are for Deep Learning and NN.
* If a data in NumPy needs to undergo deep learning, then a method called torch.from_numpy(ndarray)- which changes the data from NumPy to torch tensor.
* A method called torch.tensor.numpy() will be used for data from tensor to NumPy array.

In [40]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(array) # PyTorch reflects NumPy's default data type of float64 (can be changed using .type(torch.float32))
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [41]:
# Changing the values of numpy array by adding with 2, and checking whether its changing the values in tensor
array = array + 2
array, tensor

(array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [42]:
# Tensor to NumPy array
tensor = torch.zeros(10)
numpy_array = tensor.numpy()
tensor, numpy_array

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32))

In [43]:
# Changing the values of tensor by adding with 2, and checking whether its changing the values in numpy array
tensor = tensor + 2
tensor, numpy_array

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32))

Reproducibility
* Reproducibility in PyTorch ensures getting consistent results every single time we run the code.
* Neural Networks starts with random numbers, then tensor operations followed by updating the random numbers and repeat the cycle.
* The randomness of the numbers can be reduced in PyTorch by using ***random seed***

In [51]:
# Setting the random seed (should be seperately given for each tensor)
torch.manual_seed(42)
random_tensor_a = torch.rand(2,3)

torch.manual_seed(42)
random_tensor_b = torch.rand(2,3)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_b == random_tensor_a)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[True, True, True],
        [True, True, True]])


 # GPUs
 * with the help of Graphical Processing Units, several computational tasks can be ran in parallel.
 * Intially they were build for graphics, especially for gamings but now GPUs play a vital role in AI, ML and DL.
 * Compute Unified Device Architecture **CUDA** is a computing platform and a programming model developed by nvidia, serves as a bridge between the code and GPU by moving the tensors to GPU.
 * CUDA runs the logic of code, and GPU does heavy math computation tasks.


In [56]:
# As i have chose CPU run time, the cuda is not available
torch.cuda.is_available()

False

In [57]:
## Setting up the device agnostic code, which automatically runs on CPU or GPU by dynamically selecting the available device.
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'