<a href="https://colab.research.google.com/github/Naga-SDonepudi/PyTorch_HandsOn/blob/main/1_Fundamentals_of_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing PyTorch

In [2]:
import torch
print("PyTorch Version:", torch.__version__)

PyTorch Version: 2.9.0+cpu


## Importing Pandas, NumPy, Matplotlib

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Pandas Version:", pd.__version__)
print("NumPy Version:", np.__version__)

Pandas Version: 2.2.2
NumPy Version: 2.0.2


## Tensors
* A mutli dimensional array of numbers used to store machine learning and deep learning related data. PyTorch tensors are created using torch.tensor()

In [4]:
### Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
### Vector
vector = torch.tensor([8, 8])
vector

tensor([8, 8])

In [11]:
### Matrix
matrix = torch.tensor([[2,4],
                       [3,5]])
matrix

tensor([[2, 4],
        [3, 5]])

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
### TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
TENSOR.ndim

3

## Random Tensors
* A random tensor is a tensor whose values are randomly generated and filled with random numbers, useful for starting models, testing, and experiments.
* They are widely used in machine learning and deep learning to initialize model weights, create dummy data, and test code.
* Random numbers are so valuable, as neural networks start with random numbers and looks at data, and adjusts those numbers and so on.


In [30]:
random_tensor = torch.rand(2, 3)
random_tensor

tensor([[0.0147, 0.5518, 0.7512],
        [0.6359, 0.5581, 0.9573]])

In [31]:
random_tensor.ndim

2

In [36]:
# A random image tensor with (height, width and color channels R,G,B)
random_image_size_tensor = torch.rand(size=(186, 186, 8))
random_image_size_tensor

tensor([[[0.3337, 0.0393, 0.9357,  ..., 0.0989, 0.3151, 0.5159],
         [0.6346, 0.6741, 0.2496,  ..., 0.8531, 0.4234, 0.4397],
         [0.3846, 0.7333, 0.0225,  ..., 0.9849, 0.8550, 0.0640],
         ...,
         [0.4403, 0.0106, 0.3888,  ..., 0.1635, 0.7286, 0.3801],
         [0.2090, 0.6586, 0.2078,  ..., 0.6043, 0.4299, 0.2238],
         [0.4713, 0.8271, 0.4605,  ..., 0.1670, 0.9466, 0.6480]],

        [[0.0938, 0.9282, 0.0877,  ..., 0.2764, 0.8526, 0.6087],
         [0.5698, 0.0167, 0.5544,  ..., 0.8905, 0.6386, 0.1000],
         [0.8730, 0.9886, 0.8365,  ..., 0.0889, 0.6513, 0.3137],
         ...,
         [0.5615, 0.7535, 0.5949,  ..., 0.2280, 0.5487, 0.9058],
         [0.4382, 0.1171, 0.5097,  ..., 0.3308, 0.5521, 0.9340],
         [0.4743, 0.3771, 0.6639,  ..., 0.5517, 0.0013, 0.5215]],

        [[0.5383, 0.4721, 0.9186,  ..., 0.6815, 0.4960, 0.5889],
         [0.8481, 0.3071, 0.8992,  ..., 0.8048, 0.6058, 0.7206],
         [0.1275, 0.0976, 0.2857,  ..., 0.3577, 0.1518, 0.

In [37]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([186, 186, 8]))

## Ones and Zeros Tensors

In [45]:
zeros = torch.zeros(size=(3,4))
zeros.ndim

2

In [46]:
ones = torch.ones(size=(3,3,4))
ones.ndim

3

## Range of tensors and tensor-likes

In [57]:
## Creating a range of tensors
one_to_hundred = torch.arange(1, 101, 9)
one_to_hundred

tensor([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100])

In [58]:
## Creating tensors like
ten_ones = torch.ones_like(input=one_to_hundred)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Datatypes of Tensors


In [70]:
dt_tensor = torch.tensor([1.0, 2.0, 3.0],
                         dtype=None, # Type Data
                         device=None, # What device is tensor on
                         requires_grad=False) # Whether or not to track gradients with this tensor operation

In [71]:
dt_tensor

tensor([1., 2., 3.])

In [72]:
dt_half_tensor = dt_tensor.type(torch.HalfTensor)
dt_half_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')